#!/bin/bash -e
if [[ ! -f "/home/spark-77f05485-b638-4d1f-9983-d9/tmp/uv/uv_0.6.10_linux_amd64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-77f05485-b638-4d1f-9983-d9/tmp/uv/uv_0.6.10_linux_amd64" "$@"
